/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.northeastern.cs5500.recipe.controller;

import static com.google.common.truth.Truth.assertThat;
import static com.google.common.truth.Truth.assertWithMessage;

import edu.northeastern.cs5500.recipe.model.Comment;
import java.net.UnknownHostException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import org.junit.Assert;
import org.junit.jupiter.api.Test;

class CommentControllerTest {
    @Test
    void testRegisterCreatesReview() throws UnknownHostException {
        CommentController commentController = new CommentController();
        commentController.register();
        assertThat(commentController.getComments()).isNotEmpty();
    }

    @Test
    void testRegisterCreatesValidComment() throws UnknownHostException {
        // TODO: Why is this test failing?
        CommentController commentController = new CommentController();
        commentController.register();

        for (Comment comment : commentController.getComments()) {
            assertWithMessage(comment.getUserId()).that(comment.isValid()).isTrue();
        }
    }

    @Test
    void testCanAddComment() throws Exception {
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        String curDate = dateFormat.format(date);
        CommentController commentController = new CommentController();
        Comment comment = new Comment("patrick1107", curDate, "I love fried chicken.");
        commentController.addComment(comment);
        Assert.assertEquals(commentController.getComment("patrick1107").getUserId(), "patrick1107");
        commentController.deleteComment("patrick1107");
    }

    @Test
    void testCanReplaceComment() throws Exception {
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        String curDate = dateFormat.format(date);
        CommentController commentController = new CommentController();
        Comment comment = new Comment("patrick1107", curDate, "I love fried chicken.");
        commentController.addComment(comment);
        Comment updatedComment = new Comment("patrick1107", curDate, "agree!");
        commentController.updateCommeet(updatedComment);
        Assert.assertEquals(
                "I love fried chicken.", commentController.getComment("patrick1107").getContent());
        commentController.deleteComment("patrick1107");
    }

    @Test
    void testCanDeleteComment() throws Exception {
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        String curDate = dateFormat.format(date);
        CommentController commentController = new CommentController();
        Comment comment = new Comment("PengluYang", curDate, "Disagree!");
        commentController.addComment(comment);
        Assert.assertEquals(commentController.getComment("PengluYang").getContent(), "Disagree!");
        commentController.deleteComment("PengluYang");
        Assert.assertEquals(commentController.getComment("PengluYangn"), null);
    }
}
