/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.northeastern.cs5500.recipe.controller;

import static com.google.common.truth.Truth.assertThat;
import static com.google.common.truth.Truth.assertWithMessage;

import edu.northeastern.cs5500.recipe.model.Review;
import java.net.UnknownHostException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import org.junit.Assert;
import org.junit.jupiter.api.Test;

class ReviewControllerTest {
    @Test
    void testRegisterCreatesReview() throws UnknownHostException {
        ReviewController reviewController = new ReviewController();
        reviewController.register();
        assertThat(reviewController.getAllReviews()).isNotEmpty();
    }

    @Test
    void testRegisterCreatesValidReview() throws UnknownHostException {
        // TODO: Why is this test failing?
        ReviewController reviewController = new ReviewController();
        reviewController.register();

        for (Review review : reviewController.getAllReviews()) {
            assertWithMessage(review.getRecipeId()).that(review.isValid()).isTrue();
        }
    }

    @Test
    void testCanAddReview() throws Exception {
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        String curDate = dateFormat.format(date);
        ReviewController reviewController = new ReviewController();
        // reviewController.deleteReview("YiwenZhang_slava_chiken/YiwenZhang");
        Review review =
                new Review(
                        "YiwenZhang2",
                        curDate,
                        "Wonderful Recipe!",
                        "YiwenZhang_slava_chiken",
                        5,
                        "YiwenZhang_slava_chiken/YiwenZhang2");
        String id = ReviewController.addReview(review);
        Assert.assertEquals(
                reviewController.getReview("YiwenZhang_slava_chiken/YiwenZhang2").getRecipeId(),
                "YiwenZhang_slava_chiken");
        reviewController.deleteReview(id);
    }

    @Test
    void testCanDeleteReview() throws Exception {
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        String curDate = dateFormat.format(date);
        ReviewController reviewController = new ReviewController();
        // reviewController.deleteReview("YiwenZhang_slava_chiken/YiwenZhang");
        Review review =
                new Review(
                        "YiwenZhang1",
                        curDate,
                        "Wonderful Recipe!",
                        "YiwenZhang_slava_chiken",
                        5,
                        "YiwenZhang_slava_chiken/YiwenZhang1");

        String id = ReviewController.addReview(review);
        System.out.println(id);
        Assert.assertEquals(
                reviewController.getReview("YiwenZhang_slava_chiken/YiwenZhang1").getRecipeId(),
                "YiwenZhang_slava_chiken");
        reviewController.deleteReview(id);
        Assert.assertEquals(
                reviewController.getReview("YiwenZhang_slava_chiken/YiwenZhang1"), null);
    }
}
