/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.northeastern.cs5500.recipe.controller;

import static com.google.common.truth.Truth.assertThat;
import static com.google.common.truth.Truth.assertWithMessage;

import edu.northeastern.cs5500.recipe.model.ReviewComment;
import java.net.UnknownHostException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import org.junit.Assert;
import org.junit.jupiter.api.Test;

class ReviewCommentControllerTest {
    @Test
    void testRegisterCreatesReview() throws UnknownHostException {
        ReviewCommentController reviewCommentController = new ReviewCommentController();
        reviewCommentController.register();
        assertThat(reviewCommentController.getAllReviewComments()).isNotEmpty();
    }

    @Test
    void testRegisterCreatesValidReviewaComment() throws UnknownHostException {
        // TODO: Why is this test failing?
        ReviewCommentController reviewCommentController = new ReviewCommentController();
        reviewCommentController.register();

        for (ReviewComment reviewComment : reviewCommentController.getAllReviewComments()) {
            assertWithMessage(reviewComment.getUserId()).that(reviewComment.isValid()).isTrue();
        }
    }

    @Test
    void testCanAddReviewComment() throws Exception {
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        String curDate = dateFormat.format(date);
        ReviewCommentController reviewCommentController = new ReviewCommentController();
        // reviewCommentController.deleteReviewComment("YiwenZhang_slava_chiken/PengluYang");
        ReviewComment reviewComment =
                new ReviewComment(
                        "PengluYang1", curDate, "Disagree!", "YiwenZhang_slava_chiken/PengluYang1");
        reviewCommentController.addReviewComment(reviewComment);
        Assert.assertEquals(
                reviewCommentController
                        .getReviewComment("YiwenZhang_slava_chiken/PengluYang1")
                        .getUserId(),
                "PengluYang1");
        reviewCommentController.deleteReviewComment("YiwenZhang_slava_chiken/PengluYang1");
    }

    @Test
    void testCanDeleteReviewComment() throws Exception {
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        String curDate = dateFormat.format(date);
        ReviewCommentController reviewCommentController = new ReviewCommentController();
        // reviewCommentController.deleteReviewComment("YiwenZhang_slava_chiken/PengluYang1");
        ReviewComment reviewComment =
                new ReviewComment(
                        "PengluYang1", curDate, "Disagree!", "YiwenZhang_slava_chiken/PengluYang1");
        reviewCommentController.addReviewComment(reviewComment);

        reviewCommentController.deleteReviewComment("YiwenZhang_slava_chiken/PengluYang1");
        Assert.assertEquals(
                reviewCommentController.getReviewComment("YiwenZhang_slava_chiken/PengluYang1"),
                null);
    }
}
